language: node_js
node_js:
  - "stable"
env:
  - TEST_DIR=frontend
  - TEST_DIR=backend
cache:
  directories:
  - frontend/node_modules
  - backend/node_modules
script:
  - cd $TEST_DIR && npm install && npm run test